### ISSUE TITLE
help me!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by ZODIAC0103** [silvanohirtie/account-generator#1]
Error: Cannot find module 'node:events'
Require stack:
- /home/runner/silvanohirtie-account-generator/node_modules/discord.js/src/client/BaseClient.js
- /home/runner/silvanohirtie-account-generator/node_modules/discord.js/src/index.js
- /home/runner/silvanohirtie-account-generator/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/silvanohirtie-account-generator/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:1
    
    how do i fix dis?

**Comment by ZODIAC0103** [comment]
SyntaxError: Unexpected token '?'

**Comment by ZODIAC0103** [comment]
bitches reply me

**Comment by SrShrek** [comment]
skid lol

**Comment by silvanohirtie** [comment]
@ZODIAC0103 
Read them in order...
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Introduction#where_to_find_javascript_information
https://nodejs.org/en/docs/guides/getting-started-guide/
https://discordjs.guide/#before-you-begin
