### ISSUE TITLE
Starting the bot

### ISSUE THREAD

**Issue by Lory9102** [silvanohirtie/account-generator#42]
Hi! I tried to start the bot on repl.it and it says to me when i type in "npm start" it says
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-03-25T15_26_18_401Z-debug.log
exit status 1
And when i type in "node ." it says
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'discord.js'
Require stack:
- /home/runner/account-generator-1/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/runner/account-generator-1/index.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/account-generator-1/index.js' ]
  
  Can you help me please

**Comment by ClearlyElevated** [comment]
The error is pretty self explanatory, you don't have the discord package installed

**Comment by chrispycreme420** [comment]
install the disc package

**Comment by crxangel** [comment]
just type this "npm i " in ur terminal
and walah done
