### ISSUE TITLE
Can somebody help me with this??

### ISSUE THREAD

**Issue by ImmortalBeastZ42** [silvanohirtie/account-generator#48]
bot.login(TOKEN);
          ^

ReferenceError: TOKEN is not defined
    at Object.<anonymous> (F:\account-generator-master\index.js:237:11)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1085:14)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:950:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:790:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m

**Comment by ibenks** [comment]
try running on replit, or removing the ; after (TOKEN)

**Comment by ImmortalBeastZ42** [comment]
eh nvm I got it somehow lmao

**Comment by ImmortalBeastZ42** [comment]
anyway, thanks for trying to help though :D
